postgresql_admin_user: "postgres"
postgresql_default_auth_method: "trust"

postgresql_databases:
  - name: development
    hstore: yes
  - name: test
    hstore: yes

postgresql_users:
  - name: vagrant
    pass: supersecurepassword
    encrypted: no

postgresql_user_privileges:
  - name: vagrant
    db: development
    priv: "ALL"
  - name: vagrant
    db: test
    priv: "ALL"

postgresql_user_object_privileges:
  - name: vagrant
    db: development
    type: table
    priv: ALL
    objs: 'ALL_IN_SCHEMA'
  - name: vagrant
    db: test
    type: table
    priv: ALL
    objs: 'ALL_IN_SCHEMA'
  - name: vagrant
    db: development
    type: sequence
    priv: ALL
    objs: 'ALL_IN_SCHEMA'
  - name: vagrant
    db: test
    type: sequence
    priv: ALL
    objs: 'ALL_IN_SCHEMA'
